server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    add_header Cross-Origin-Opener-Policy same-origin always;
    add_header Cross-Origin-Embedder-Policy require-corp always;

    location ^~ /pyodide/ {
        try_files $uri =404;
    }

    location ^~ /js/ {
        try_files $uri =404;
    }

    location ^~ /static/ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
